### ISSUE TITLE
Checklist for V2020a

### ISSUE THREAD

**Issue by sunt05** [Urban-Meteorology-Reading/SUEWS#106]
## New Features
- [x] iterative surface temperature
- [x]  adaptive selection for roughness length for heat 
- [x] irrigation over crop with refilling to maintain water level

## Code Health
- [x] update release identifier: [`progname` in `suews_ctrl_const.f95`](../../SUEWS-SourceCode/suews_ctrl_const.f95)
- [ ] ~~update test identifier: [`name_exe` in `BTS_config.nml`](../../Test/code/BTS_config.nml)~~
- [x] run simple test:
  - [ ] set up test folder for the new release: `Test/BaseRun/$release_ver`
  - [ ] use `make test` in the root folder for testing

**Docs**
- [ ] update [scheme descriptions](../../docs/source/parameterisations-and-sub-models.rst) if any.
- [ ] update [option descriptions](../../docs/source/input_files/RunControl/RunControl.rst) and relevant csv files if any.

**Additional Remarks**
