### ISSUE TITLE
release 2018c

### ISSUE THREAD

**Issue by sunt05** [Urban-Meteorology-Reading/SUEWS#15]
- [x] benchmark report, Urban-Meteorology-Reading/SUEWS-docs#34
- [x] binary executable and sample data bundles
- [x] add relationship between SuPy and SUEWS in docs: 
     - [x] Urban-Meteorology-Reading/SUEWS-docs#35
     - [x] Urban-Meteorology-Reading/SUEWS-docs#33
